[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'Shougo/unite.vim'

[[plugins]]
repo =  'Shougo/neomru.vim'

[[plugins]]
repo =  "tyru/caw.vim.git"

[[plugins]]
repo =  'scrooloose/nerdtree'

[[plugins]]
repo =  'jistr/vim-nerdtree-tabs'

[[plugins]]
repo =  'mattn/emmet-vim'

[[plugins]]
repo =  'vim-scripts/grep.vim'

[[plugins]]
repo =  'Shougo/neocomplcache'

[[plugins]]
repo =  'Shougo/neoyank.vim'

[[plugins]]
repo =  'tomtom/tcomment_vim'

[[plugins]]
repo =  'tpope/vim-surround'

[[plugins]]
repo =  'Townk/vim-autoclose'

[[plugins]]
repo =  'rhysd/accelerated-jk'

[[plugins]]
repo =  'thinca/vim-quickrun'

[[plugins]]
repo =  'ctrlpvim/ctrlp.vim'

[[plugins]]
repo =  'thinca/vim-qfreplace'

[[plugins]]
repo =  'tpope/vim-fugitive'

[[plugins]]
repo =  'scrooloose/syntastic'

